# 01.A: Array-based programming with NumPy
It offers a high-performace rich functional vectorized `n-dimentional` array type called `ndarray` which is in implemented in C. It's the prefered Python array **implementation** and many of the other *libraries* we'll be using are built on or depend on it.

1. number 1
1. number 2
3. number 4

Let's import it.

* item 1
* item 2
* item 3

$\frac{12}{100}$


$\Sigma_{i = 1}^n \sqrt{(y - x)^2}$

In [1]:
import numpy as np

## Creating simple one-dimentional arrays
Let's create a simple integer array and another float array from scrach.

In [2]:
iarr = np.array([1, 3, 5, 7, 9, 11])
farr = np.array([0.00, 0.05, 0.10, 0.15, 0.20, 0.25, 0.30, 0.35])

print(iarr)
print(farr)

[ 1  3  5  7  9 11]
[0.   0.05 0.1  0.15 0.2  0.25 0.3  0.35]


We can also create an array whose elements are all zeros or ones

In [3]:
all_zeros = np.zeros(10)
all_ones = np.ones(12)

print(all_zeros)
print(all_ones)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


## Array attributes
Let's see checkout some attributes of these arrays. First here is the type of these array objects

In [4]:
type(iarr)

numpy.ndarray

In [5]:
type(farr)

numpy.ndarray

Both of these objects are of the numpy `ndarray` type: the fundamental data structure in NumPy. Let's see what type are the elements.

In [6]:
iarr.dtype

dtype('int64')

In [7]:
farr.dtype

dtype('float64')

How many elements are in each array?

In [8]:
iarr.size 

6

In [9]:
farr.size 

8

We can also find out their dimensions using the `ndim` attribute. As we know both are one-dimensional arrays.

In [10]:
iarr.ndim

1

In [11]:
farr.ndim

1

We can also find out the shapes of these arrays: how many elements in each dimension.

In [12]:
iarr.shape

(6,)

In [13]:
farr.shape

(8,)

## Reshaping arrays
We can reshape these one-dimentional arrays into multiple-dimentional arrays. For example, let's create a new 2D array with 3 rows and 2 columnsby by reshaping `iarr`. 

In [14]:
i2d = iarr.reshape(3, 2)

Here is the dimentions and shape of the new 2D array.

In [15]:
print(i2d.ndim)
print(i2d.shape)

2
(3, 2)


Similarly, let's create a new 3D array (an array of 2D arrays) by reshaping `farr` with two elements in every dimension.

In [16]:
f3d = farr.reshape(2,2,2)

Here is the dimentions and shape of the new 3D array.

In [17]:
print(f3d.ndim)
print(f3d.shape)

3
(2, 2, 2)


## Creating multi-dimentional arrays
We can also create multi-dimentional arrays from scrach. Keep in mind that a 2D array is an array of 1D array. And 3D array is an array of 2D arrays, and so on. Here is a 2D array made of two 1D arrays: one with 10 zeros and another with 10 ones. Each 1D array becomes a row in the new 2D array.

In [18]:
f2d = np.array([np.zeros(10), np.ones(10)])

print(f2d)
print("ndim: ", f2d.ndim)
print("shape: ", f2d.shape)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
ndim:  2
shape:  (2, 10)


Let's create a 3D array that is an array of 3 2D arrays

In [19]:
f3d = np.array([f2d, f2d, f2d])

print(f3d)
print("ndim: ", f3d.ndim)
print("shape: ", f3d.shape)

[[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]

 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]

 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]]
ndim:  3
shape:  (3, 2, 10)


We can also use the `full` function to create an array of any dimentions (the first argument) and populated with a a given value (the second argument). 

In [20]:
i1d = np.full(4, 7)
i2d = np.full((5,7), 3)
i3d = np.full((3, 2, 7), 9)

print("\nID array:\n", i1d)
print("\n2D array:\n", i2d)
print("\n3D array:\n", i3d) 


ID array:
 [7 7 7 7]

2D array:
 [[3 3 3 3 3 3 3]
 [3 3 3 3 3 3 3]
 [3 3 3 3 3 3 3]
 [3 3 3 3 3 3 3]
 [3 3 3 3 3 3 3]]

3D array:
 [[[9 9 9 9 9 9 9]
  [9 9 9 9 9 9 9]]

 [[9 9 9 9 9 9 9]
  [9 9 9 9 9 9 9]]

 [[9 9 9 9 9 9 9]
  [9 9 9 9 9 9 9]]]


## Ranges
We can also create an array from a range of values. Here are the integers from 0 all the way to 100

In [21]:
np.arange(101)

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

Here is an array with elements ranging from 3(inclusive) to 13 (exclusive)

In [22]:
nums = np.arange(3, 13)

print(nums)

[ 3  4  5  6  7  8  9 10 11 12]


Here is another array with all all the numbers between 3 and 100 that are multiple of 3 (.

In [23]:
np.arange(3, 100, step=3)

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51,
       54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

Sometimes you want to take a closed interval $[a,b]$ and generate $n$ equally sparated numbers within that interval. We use the `np.linspace` function for that. For example, here 9 numbers equally spaced within the interval $[2,4]$ including 2 and 4.

In [24]:
np.linspace(2, 4, num=9)

array([2.  , 2.25, 2.5 , 2.75, 3.  , 3.25, 3.5 , 3.75, 4.  ])

And if we want to fill the array with a range of values, use the `np.arange` or `np.linespace` functions as the second argument. 

In [25]:
i1d = np.full(4, np.arange(4))
i2d = np.full((5,7), np.arange(7))
i3d = np.full((3, 2, 9), np.linspace(3, 4, num=9))

print("\nID array:\n", i1d)
print("\n2D array:\n", i2d)
print("\n3D array:\n", i3d)


ID array:
 [0 1 2 3]

2D array:
 [[0 1 2 3 4 5 6]
 [0 1 2 3 4 5 6]
 [0 1 2 3 4 5 6]
 [0 1 2 3 4 5 6]
 [0 1 2 3 4 5 6]]

3D array:
 [[[3.    3.125 3.25  3.375 3.5   3.625 3.75  3.875 4.   ]
  [3.    3.125 3.25  3.375 3.5   3.625 3.75  3.875 4.   ]]

 [[3.    3.125 3.25  3.375 3.5   3.625 3.75  3.875 4.   ]
  [3.    3.125 3.25  3.375 3.5   3.625 3.75  3.875 4.   ]]

 [[3.    3.125 3.25  3.375 3.5   3.625 3.75  3.875 4.   ]
  [3.    3.125 3.25  3.375 3.5   3.625 3.75  3.875 4.   ]]]


## Flattening multi-dimentional arrays
We can convert a multi dimentional array into a flat one-dimentional array using `np.flatten()` or `np.ravel()`

In [26]:
i3d.flatten()

array([3.   , 3.125, 3.25 , 3.375, 3.5  , 3.625, 3.75 , 3.875, 4.   ,
       3.   , 3.125, 3.25 , 3.375, 3.5  , 3.625, 3.75 , 3.875, 4.   ,
       3.   , 3.125, 3.25 , 3.375, 3.5  , 3.625, 3.75 , 3.875, 4.   ,
       3.   , 3.125, 3.25 , 3.375, 3.5  , 3.625, 3.75 , 3.875, 4.   ,
       3.   , 3.125, 3.25 , 3.375, 3.5  , 3.625, 3.75 , 3.875, 4.   ,
       3.   , 3.125, 3.25 , 3.375, 3.5  , 3.625, 3.75 , 3.875, 4.   ])

In [27]:
i3d.ravel()

array([3.   , 3.125, 3.25 , 3.375, 3.5  , 3.625, 3.75 , 3.875, 4.   ,
       3.   , 3.125, 3.25 , 3.375, 3.5  , 3.625, 3.75 , 3.875, 4.   ,
       3.   , 3.125, 3.25 , 3.375, 3.5  , 3.625, 3.75 , 3.875, 4.   ,
       3.   , 3.125, 3.25 , 3.375, 3.5  , 3.625, 3.75 , 3.875, 4.   ,
       3.   , 3.125, 3.25 , 3.375, 3.5  , 3.625, 3.75 , 3.875, 4.   ,
       3.   , 3.125, 3.25 , 3.375, 3.5  , 3.625, 3.75 , 3.875, 4.   ])

## Indexing and slicing
Let's start with a 2D array (4 rows by 5 columns

In [28]:
a = np.arange(1, 100, 5).reshape(4, 5)
print(a)

[[ 1  6 11 16 21]
 [26 31 36 41 46]
 [51 56 61 66 71]
 [76 81 86 91 96]]


In [29]:
np.arange(1, 100, 5).size

20

NumPy uses zero-based indexing and gives different ways to index and/or slice arrays. Let's see a few examples.

Here is the first element (row 0 and column 0):

In [30]:
a[0,0]

1

And the last element (row 3 and column 4):

In [31]:
a[3,4]

96

The first row:

In [32]:
a[0,:]

array([ 1,  6, 11, 16, 21])

The last row: 

In [33]:
a[3,:]

array([76, 81, 86, 91, 96])

The first three rows:

In [34]:
a[:3, :]

array([[ 1,  6, 11, 16, 21],
       [26, 31, 36, 41, 46],
       [51, 56, 61, 66, 71]])

The last two rows:

In [35]:
a[2:, :]

array([[51, 56, 61, 66, 71],
       [76, 81, 86, 91, 96]])

The second and last rows (starting at row 1, ending at 1 + the desired row, step = 2):

In [36]:
a[1:4:2,:]

array([[26, 31, 36, 41, 46],
       [76, 81, 86, 91, 96]])

The first column:


In [37]:
a[:,0]

array([ 1, 26, 51, 76])

The second column: 

In [38]:
 a[:,1]

array([ 6, 31, 56, 81])

The last column:

In [39]:
a[:,4]

array([21, 46, 71, 96])

The first and last columns (starting at column 0, ending at 1 + desired column, step = 4):

In [40]:
a[:,0:5:4]

array([[ 1, 21],
       [26, 46],
       [51, 71],
       [76, 96]])

All the columns except the first two:

In [41]:
a[:, 2:]

array([[11, 16, 21],
       [36, 41, 46],
       [61, 66, 71],
       [86, 91, 96]])

All the columns except the last three:

In [42]:
a[:, :2]

array([[ 1,  6],
       [26, 31],
       [51, 56],
       [76, 81]])

The whole array:

In [43]:
a

array([[ 1,  6, 11, 16, 21],
       [26, 31, 36, 41, 46],
       [51, 56, 61, 66, 71],
       [76, 81, 86, 91, 96]])

In [44]:
a[:,:]

array([[ 1,  6, 11, 16, 21],
       [26, 31, 36, 41, 46],
       [51, 56, 61, 66, 71],
       [76, 81, 86, 91, 96]])

In [45]:
a[::,::]

array([[ 1,  6, 11, 16, 21],
       [26, 31, 36, 41, 46],
       [51, 56, 61, 66, 71],
       [76, 81, 86, 91, 96]])

The middle three columns of the middle two rows:

In [46]:
a[1:3:1, 1:4:1]

array([[31, 36, 41],
       [56, 61, 66]])

### Consitional expressions
We can also use array boolean expressions to extract array elements. For example, here is an array of all the odd elements in `a`:

In [47]:
a[a % 2 != 0]

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

And here are only the elements that are < 50:

In [48]:
a[a < 50]

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46])

We can use these boolean expressions with the `np.where` to return arrays with certain properties. For example, the following zero out all the non-odd elements in the array `a`

In [49]:
np.where(a % 2 != 0, a, 0)

array([[ 1,  0, 11,  0, 21],
       [ 0, 31,  0, 41,  0],
       [51,  0, 61,  0, 71],
       [ 0, 81,  0, 91,  0]])

while the following statement returns an array where any element with value between 11 and 60 is replaced with -1:

In [50]:
np.where(np.logical_and(a >= 11, a <= 60), -1, a)

array([[ 1,  6, -1, -1, -1],
       [-1, -1, -1, -1, -1],
       [-1, -1, 61, 66, 71],
       [76, 81, 86, 91, 96]])

## Fancy indexing
We slice an array using an array of indices. Given the array 

In [51]:
a = np.arange(1, 100).reshape(33, 3)

print(a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]
 [19 20 21]
 [22 23 24]
 [25 26 27]
 [28 29 30]
 [31 32 33]
 [34 35 36]
 [37 38 39]
 [40 41 42]
 [43 44 45]
 [46 47 48]
 [49 50 51]
 [52 53 54]
 [55 56 57]
 [58 59 60]
 [61 62 63]
 [64 65 66]
 [67 68 69]
 [70 71 72]
 [73 74 75]
 [76 77 78]
 [79 80 81]
 [82 83 84]
 [85 86 87]
 [88 89 90]
 [91 92 93]
 [94 95 96]
 [97 98 99]]


Here is an array containing first, third and tenth rows of `a`:

In [52]:
a[[0, 2, 9]]

array([[ 1,  2,  3],
       [ 7,  8,  9],
       [28, 29, 30]])

And here is an array containing the odd rows only of `a`:

In [53]:
a[np.arange(1,33, 2)]

array([[ 4,  5,  6],
       [10, 11, 12],
       [16, 17, 18],
       [22, 23, 24],
       [28, 29, 30],
       [34, 35, 36],
       [40, 41, 42],
       [46, 47, 48],
       [52, 53, 54],
       [58, 59, 60],
       [64, 65, 66],
       [70, 71, 72],
       [76, 77, 78],
       [82, 83, 84],
       [88, 89, 90],
       [94, 95, 96]])

## Array arithmetic
Given to arrays of the same shape, we can perform element-wise arthmetic operations on these arrays. 

Let arrays `a` and `b` be the following:

In [54]:
a = np.arange(1, 19, 2).reshape(3,3)
b = np.arange(2, 19, 2).reshape(3,3)

In [55]:
a

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17]])

In [56]:
b

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

We can now perform the following element-by-element arithmetic and logical operations without any loops.

In [57]:
a + b

array([[ 3,  7, 11],
       [15, 19, 23],
       [27, 31, 35]])

In [58]:
a - b

array([[-1, -1, -1],
       [-1, -1, -1],
       [-1, -1, -1]])

In [59]:
a * b

array([[  2,  12,  30],
       [ 56,  90, 132],
       [182, 240, 306]])

In [60]:
a / b

array([[0.5       , 0.75      , 0.83333333],
       [0.875     , 0.9       , 0.91666667],
       [0.92857143, 0.9375    , 0.94444444]])

In [61]:
b % a

array([[0, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [62]:
a < b

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [63]:
b < a

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

## Matrix operations
Say that we have the following matrices:

$ A = \begin{bmatrix} 1 & 2 & 1 \\ 3 & 0 & 1 \\ 0 & 2 & 4 \end{bmatrix}$

$ B = \begin{bmatrix} 3 & 1 & 2 \\ 1 & 1 & 0 \\ 1 & 3 & 1 \end{bmatrix}$

$ v = \begin{bmatrix} 1 \\ 3  \\ 2  \end{bmatrix}$

We can create three numpy arrays for them as follows:

In [64]:
A = np.array([[1,2,1], [3, 0, 1], [0, 2, 4]])
B= np.array([3, 1, 2, 1, 1, 0, 1, 3, 1]).reshape(3,3)
v = np.array([1, 3, 2]).reshape(3,1)

print(A)
print(B)
print(v)

[[1 2 1]
 [3 0 1]
 [0 2 4]]
[[3 1 2]
 [1 1 0]
 [1 3 1]]
[[1]
 [3]
 [2]]


Now can now perform the matrix operations we know from linear algebra. Here are a few matrix expressions. 

$A + B$:

In [65]:
A + B

array([[4, 3, 3],
       [4, 1, 1],
       [1, 5, 5]])

$3B$:

In [66]:
3 * B

array([[9, 3, 6],
       [3, 3, 0],
       [3, 9, 3]])

$A - 3B$:

In [67]:
A - 3 * B

array([[-8, -1, -5],
       [ 0, -3,  1],
       [-3, -7,  1]])

$A \times B$:

In [68]:
A.dot(B)

array([[ 6,  6,  3],
       [10,  6,  7],
       [ 6, 14,  4]])

which is not the same as $B \times A$:

In [69]:
B.dot(A)

array([[ 6, 10, 12],
       [ 4,  2,  2],
       [10,  4,  8]])

And here is the determinant of $A$ which is denoted by $|A|$:

In [70]:
np.linalg.det(A)

-19.999999999999996

And the transpose of $B$ which is denoted as $B^T$:

In [71]:
B.T

array([[3, 1, 1],
       [1, 1, 3],
       [2, 0, 1]])

Notice that $v \times A$ is not valid because dimention misalignment. Uncomment the statement below to see the error

In [72]:
# v.dot(A)

However, $A \times v$ is valid:

In [73]:
A.dot(v)

array([[ 9],
       [ 5],
       [14]])

And so is  $v^T \times A$:

In [74]:
v.T.dot(A)

array([[10,  6, 12]])

Finally we can calculate the inverse matrix of $A$ denoted as $A^{-1}

In [75]:
Ainv = np.linalg.inv(A)

which we can verify by the multipication $A \times A^{-1}$

In [76]:
A.dot(np.linalg.inv(A)).round()

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [-0.,  0.,  1.]])

which should be the same as the identity matrix $I$.

In [77]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Universal element-wise functions
Given the array $A$ we can caluculat the square root, absolute value, sin, cos, etc of its elements 

In [78]:
A

array([[1, 2, 1],
       [3, 0, 1],
       [0, 2, 4]])

In [79]:
np.sqrt(A)

array([[1.        , 1.41421356, 1.        ],
       [1.73205081, 0.        , 1.        ],
       [0.        , 1.41421356, 2.        ]])

In [80]:
np.abs(A)

array([[1, 2, 1],
       [3, 0, 1],
       [0, 2, 4]])

In [81]:
np.sin(A)

array([[ 0.84147098,  0.90929743,  0.84147098],
       [ 0.14112001,  0.        ,  0.84147098],
       [ 0.        ,  0.90929743, -0.7568025 ]])

In [82]:
np.exp(A)

array([[ 2.71828183,  7.3890561 ,  2.71828183],
       [20.08553692,  1.        ,  2.71828183],
       [ 1.        ,  7.3890561 , 54.59815003]])

## Statistical functions
There are also functions for summerizing arrays. Here are some examples:

In [83]:
A

array([[1, 2, 1],
       [3, 0, 1],
       [0, 2, 4]])

In [84]:
np.max(A)

4

In [85]:
A.max()

4

In [86]:
np.min(A)

0

In [87]:
A.min()

0

In [88]:
np.sum(A)

14

In [89]:
A.sum()

14

In [90]:
np.cumsum(A)   # Cummulative sum

array([ 1,  3,  4,  7,  7,  8,  8, 10, 14])

In [91]:
A.cumsum()     # Cummulative sum

array([ 1,  3,  4,  7,  7,  8,  8, 10, 14])

In [92]:
np.mean(A)     # average

1.5555555555555556

In [93]:
A.mean()       # average

1.5555555555555556

In [94]:
np.var(A)      # variance

1.5802469135802468

In [95]:
A.var()        # variance

1.5802469135802468

In [96]:
np.median(A)   # median

1.0

## Random numbers

We can also generate arrays of certain dimentions filled with random numbers using the `np.random.randn` function. The generated numbers are sampled from a normal Guassian) distribution with 0 mean and 1 variace. Here is 2D array ($4 \times 5$):

In [97]:
np.random.randn(4,5)

array([[ 0.1504599 , -1.54276132,  1.86371847, -0.41172788, -1.21191735],
       [-1.65152275,  1.30945645,  0.15379032,  0.56587434, -1.23171065],
       [ 0.15039716, -0.00935314,  1.21383113, -0.28899702, -0.23905629],
       [ 0.98869611,  0.80169239,  2.20215536, -0.28109672, -0.36992699]])

which is equivalent to:

In [98]:
np.random.normal(size=(4, 5))

array([[ 1.03012758,  0.18088401,  0.62068695, -0.95785984, -0.26151262],
       [-0.40779207, -1.04714339,  0.10403351,  0.67042491, -0.25250776],
       [ 0.83411817,  0.05416066, -0.47361293, -0.03552149, -1.42660043],
       [ 1.94337149,  1.90571345,  1.87555265,  0.2524749 , -0.03560416]])

or

In [99]:
np.random.normal(loc=0, scale=1, size=(4, 5))

array([[ 1.49981753, -1.49883121, -1.17234127, -0.38384354, -0.26171825],
       [-0.30675867,  0.03545516,  0.98524586,  0.36902094,  2.34546059],
       [-0.0479879 , -0.84135049, -0.02573568,  1.55317242, -0.15702619],
       [ 0.93334466, -0.52884597,  0.32978319,  2.68536452, -1.60521158]])

But if you want random integers within a given range, use `np.random.randint`. For example, the following simulates rolling a die 100 times.

In [100]:
np.random.randint(1, 7, 100)

array([5, 6, 1, 1, 5, 3, 4, 3, 6, 2, 2, 3, 3, 2, 4, 4, 3, 6, 6, 1, 4, 1,
       2, 5, 1, 5, 2, 4, 3, 6, 5, 6, 3, 3, 2, 6, 4, 1, 6, 5, 5, 1, 2, 6,
       5, 4, 6, 1, 4, 6, 4, 4, 3, 2, 4, 3, 3, 1, 5, 2, 1, 1, 4, 1, 2, 6,
       2, 5, 4, 6, 1, 6, 2, 6, 3, 4, 4, 6, 4, 1, 3, 5, 1, 2, 1, 1, 4, 5,
       4, 5, 4, 3, 2, 4, 3, 6, 6, 6, 3, 2])

A lot of times we want to be able to reproduce our randomized experiments. To so so we need to seed a pseudorandom generator and then use that generator to generate random numbers. Here is an a random generator seeded with the value 17.

In [101]:
rgen = np.random.RandomState(17)

Now we can use this generator to create random arrays. Here are three random arrays: $2 \times 4 \times 3$, $3 \times 3$, and one-dimentional.

In [102]:
rgen.randint(1, 7, size=(2, 4, 3))

array([[[2, 2, 1],
        [6, 5, 5],
        [5, 2, 2],
        [2, 1, 3]],

       [[3, 4, 4],
        [4, 2, 2],
        [2, 6, 6],
        [2, 1, 6]]])

In [103]:
rgen.randn(3,3)

array([[-0.98525081, -1.05703547, -2.05153126],
       [ 1.21389446, -0.3884363 ,  1.37570986],
       [-0.07229169, -0.07374186,  0.0852946 ]])

In [104]:
rgen.normal(loc=10, scale=2, size=100)

array([ 9.65202716,  8.15966352,  8.73116601, 10.50258947, 12.44943781,
       10.17881968,  8.34026135, 10.94509223,  8.17656093,  9.70888585,
        7.98072405, 10.36662361, 10.47850307, 12.53445862, 11.84434913,
       11.00458003, 10.63107922, 10.70567988,  9.06736143, 10.67145563,
       10.689168  ,  9.83351693,  9.28495304, 11.77781781,  4.59393349,
        7.80193631,  9.95760942, 13.47938725, 13.41517309, 10.95356487,
       10.6873841 ,  9.55517877, 10.81832625,  8.4658072 ,  7.86551697,
        9.1114213 , 10.45921952, 11.70502529, 10.83455575, 12.02425194,
       11.3696746 ,  7.5998159 ,  8.74145095, 11.64588045,  8.15715242,
        9.84681331,  8.55671935, 14.47809847,  9.60828963, 10.34588629,
        8.14942385, 10.03900555, 11.14511331, 10.47095418, 10.06738514,
        9.98577212, 12.55131359, 12.00228501, 11.83816279, 11.10247757,
       11.45638389, 10.87880382,  4.80454537, 10.13676316, 10.13206777,
        8.55831996,  9.28222966,  4.50673256, 12.25536122,  9.96

## Sorting and unique values
Let's have the following array.

In [105]:
dat = np.random.randint(1,11, 20)

print(dat)

[ 1  5  6  9  1  5 10  5  6 10  5  8  9  4  2  1  7  7  8  9]


We can sort this array in-place like this:

In [106]:
dat.sort()

print(dat)

[ 1  1  1  2  4  5  5  5  5  6  6  7  7  8  8  9  9  9 10 10]


And to get the unique values the make up this array, we write:

In [107]:
np.unique(dat)

array([ 1,  2,  4,  5,  6,  7,  8,  9, 10])

## Concatenating arrays along an anxis
We can take two arrays and concatenate them along an axis. For example, given the 2D arrays:

In [108]:
print(A)
print(B)

[[1 2 1]
 [3 0 1]
 [0 2 4]]
[[3 1 2]
 [1 1 0]
 [1 3 1]]


Here is the concatenagion af A and B along the row axis (axis = 0: adding new rows)

In [109]:
np.concatenate([A, B], axis=0)

array([[1, 2, 1],
       [3, 0, 1],
       [0, 2, 4],
       [3, 1, 2],
       [1, 1, 0],
       [1, 3, 1]])

And here is the concatenagion af A and B along the column axis (axis = 1: adding new columns)

In [110]:
np.concatenate([A, B], axis=1)

array([[1, 2, 1, 3, 1, 2],
       [3, 0, 1, 1, 1, 0],
       [0, 2, 4, 1, 3, 1]])

## CHALLENGE 01
Given the two array:

In [111]:
A1 = np.array([[ 6, 10, 12],
       [ 4,  2,  2],
       [10,  4,  8]])

and

In [112]:
B1 = np.array([[ 2, 5],
       [ 1,  0],
       [3,  2]])

Multiplying these two matrices gives us:

In [113]:
A1 @ B1

array([[58, 54],
       [16, 24],
       [48, 66]])

Create a Python function that given to compatible matrices $A$ and $B$ performs the multiplication $A \times B$  using pure python (use lists and loops) and no NumPy. Test your function by multiplying the `A1` and `B1` arrays above.

In [114]:
# TODO