# 01.B: Organizing data into  Series and DataFrames with Pandas
Pandas comes with two main data structures: Series and DataFrame. A Series is like a dictionary with keys (also called indexes) and values. A DataFrame represents tabular data with one or more columns.

To use pandas, we first need to import it. Let's also import numpy.

In [1]:
import numpy as np
import pandas as pd

We can now create series and dataframes
## Series

### Creating a Series
We can create a Serices by providing an array of values.

In [2]:
s1 = pd.Series([10,20,30,40,50])
print(s1)

0    10
1    20
2    30
3    40
4    50
dtype: int64


Since we did not provide indexes for our data, numeric zero-based indexes (much like those for arrays) will be automatically provided.

We can also create a Series by providing custom indexes.

In [3]:
s2 = pd.Series([1,2,3,4,5], index=['a','b','c','d','e'])
print(s2)


a    1
b    2
c    3
d    4
e    5
dtype: int64


Notice that indexes are not required to be unique. For example, we can create a Series with duplicate indexes

In [4]:
s3 = pd.Series([1,2,3,4,5], index=['a','b','b','c','c']) 
print(s3)

a    1
b    2
b    3
c    4
c    5
dtype: int64


We can create a Series from NumPy arrays.

In [5]:
snp = pd.Series(np.arange(2, 11, 2), index=['A','B','C','D','F']) 
print(snp)

A     2
B     4
C     6
D     8
F    10
dtype: int64


And indexes could be ranges

In [6]:
s4 = pd.Series(np.arange(2, 11, 2), index=np.arange(1, 6)) 
print(s4)

1     2
2     4
3     6
4     8
5    10
dtype: int64


### Accessing elements in a Series
We can use the indexes to extract and/or slice elements within a Series. For example, given the Series `s1`:

In [7]:
s1

0    10
1    20
2    30
3    40
4    50
dtype: int64

Here is its element at index 0:

In [8]:
s1[0]

10

and its elements at index 2, 3:

In [9]:
s1[[2,3]]

2    30
3    40
dtype: int64

or at the index range from 2 upto but not equal to 4

In [10]:
s1[2:4]

2    30
3    40
dtype: int64

And given the Series `s2`:

In [11]:
s2

a    1
b    2
c    3
d    4
e    5
dtype: int64

Here is the element at index 'c' followed by the elements from index 'b' to index 'd'

In [12]:
s2['c']

3

In [13]:
s2['b':'d']

b    2
c    3
d    4
dtype: int64

And for a Series with duplicate indexes such as:

In [14]:
s3

a    1
b    2
b    3
c    4
c    5
dtype: int64

using a duplicate index returns a Series of all the elements with that index.

In [15]:
s3['b']

b    2
b    3
dtype: int64

The above use of indexes is the same as using `.loc[]` with indexes between `[` and `]`. That is

In [16]:
print(snp['A':'D'])
print(s3['b'])

A    2
B    4
C    6
D    8
dtype: int64
b    2
b    3
dtype: int64


is the same as:

In [17]:
print(snp.loc['A':'D'])
print(s3.loc['b'])

A    2
B    4
C    6
D    8
dtype: int64
b    2
b    3
dtype: int64


But sometimes we want to use the position of the index rather than its actual value to access elements within a Series. We can use `.iloc[]` with zero-based numeric indexe positions between `[` and `]`. The postion 0 means the first index. Given the Series:

In [18]:
snp

A     2
B     4
C     6
D     8
F    10
dtype: int64

We can access its first element:

In [19]:
snp.iloc[0]

2

And its last element:

In [20]:
snp.iloc[snp.size - 1]

10

With `.iloc` we can index and slice a Series in exactly the same way we can a one-dimensional numpy array. Here is for example how you select every other element in a Series.

In [21]:
snp.iloc[0::2]

A     2
C     6
F    10
dtype: int64

And speaking of numpy, we can extract the values of a Series as a numpy array

In [22]:
snp.values

array([ 2,  4,  6,  8, 10])

We can also extract its indexes as an array also:

In [23]:
snp.index

Index(['A', 'B', 'C', 'D', 'F'], dtype='object')

## DataFrames
A data frame is a table with columns and rows. You can think of each column on a DataFrame as a Series sharing the same indexes with all other columns. Each column has a name that can be used to access it.

### Creating DataFrames
The easiest way to create a DataFrame is by using a dictionary of arrays. The keys of this dictionary will become column names. Here is a DataFrame with 4 by 9 multiplication table.

In [24]:
mtable = pd.DataFrame({
    'byOne': [1,2, 3, 4, 5, 6, 7, 8, 9],
    'byTwo': [2, 4, 6, 8, 10, 12, 14, 16, 18],
    'byThree': [3, 6, 9, 12, 15, 18, 21, 24, 27],
    'byFour': [4, 8, 12, 16, 20, 24, 28, 32, 36]
})

mtable

byOne  byTwo  byThree  byFour
0      1      2        3       4
1      2      4        6       8
2      3      6        9      12
3      4      8       12      16
4      5     10       15      20
5      6     12       18      24
6      7     14       21      28
7      8     16       24      32
8      9     18       27      36

Since we did not provide indexes, pandas will create zero-based numeric indexed for us, just like it does for a Series.

We can use numpy arrays to create the same table:

In [25]:
mtable = pd.DataFrame({
    'byOne': np.arange(1, 10),
    'byTwo': 2 * np.arange(1, 10),
    'byThree': 3 * np.arange(1, 10),
    'byFour': 4 * np.arange(1, 10)
})

print(mtable)

   byOne  byTwo  byThree  byFour
0      1      2        3       4
1      2      4        6       8
2      3      6        9      12
3      4      8       12      16
4      5     10       15      20
5      6     12       18      24
6      7     14       21      28
7      8     16       24      32
8      9     18       27      36


We can create a DataFrame from a two-dimensional array. Given an array:

In [26]:
table = np.array([
    np.arange(1, 10),
    2 * np.arange(1, 10),
    3 * np.arange(1, 10),
    4 * np.arange(1, 10)
]).T

print(table)

[[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]
 [ 4  8 12 16]
 [ 5 10 15 20]
 [ 6 12 18 24]
 [ 7 14 21 28]
 [ 8 16 24 32]
 [ 9 18 27 36]]


we can create a DataFrame from it.

In [27]:
mtable = pd.DataFrame(table)

mtable

0   1   2   3
0  1   2   3   4
1  2   4   6   8
2  3   6   9  12
3  4   8  12  16
4  5  10  15  20
5  6  12  18  24
6  7  14  21  28
7  8  16  24  32
8  9  18  27  36

Since we did not provide column names or indexes, Pandas provided numeric zero-based column names and indexes for us. We can provide custom column names to this DataFrame after it was created

In [28]:
mtable.columns= ['A', 'B', 'C', 'D']
mtable

A   B   C   D
0  1   2   3   4
1  2   4   6   8
2  3   6   9  12
3  4   8  12  16
4  5  10  15  20
5  6  12  18  24
6  7  14  21  28
7  8  16  24  32
8  9  18  27  36

We can provide the column names at the time of creating the DataFrame.

In [29]:
mt = pd.DataFrame(table, columns=['byOne', 'byTwo', 'byThree', 'byFour'])

mt

byOne  byTwo  byThree  byFour
0      1      2        3       4
1      2      4        6       8
2      3      6        9      12
3      4      8       12      16
4      5     10       15      20
5      6     12       18      24
6      7     14       21      28
7      8     16       24      32
8      9     18       27      36

We can also provide custom indexes.

In [30]:
mt = pd.DataFrame(table, 
                  columns=['byOne', 'byTwo', 'byThree', 'byFour'],
                  index=['x1', 'x2', 'x3', 'x4', 'x5', 'x6', 'x7', 'x8', 'x9'])

mt

byOne  byTwo  byThree  byFour
x1      1      2        3       4
x2      2      4        6       8
x3      3      6        9      12
x4      4      8       12      16
x5      5     10       15      20
x6      6     12       18      24
x7      7     14       21      28
x8      8     16       24      32
x9      9     18       27      36

We can convert the content of a DataFrame to a numpy array:

In [31]:
mt.values

array([[ 1,  2,  3,  4],
       [ 2,  4,  6,  8],
       [ 3,  6,  9, 12],
       [ 4,  8, 12, 16],
       [ 5, 10, 15, 20],
       [ 6, 12, 18, 24],
       [ 7, 14, 21, 28],
       [ 8, 16, 24, 32],
       [ 9, 18, 27, 36]])

We can get its colum names:

In [32]:
mt.columns

Index(['byOne', 'byTwo', 'byThree', 'byFour'], dtype='object')

and its indexes:

In [33]:
mt.index

Index(['x1', 'x2', 'x3', 'x4', 'x5', 'x6', 'x7', 'x8', 'x9'], dtype='object')

### Adding new columns and rows to an existing DataFrame
Given the DataFrame:

In [34]:
mt

byOne  byTwo  byThree  byFour
x1      1      2        3       4
x2      2      4        6       8
x3      3      6        9      12
x4      4      8       12      16
x5      5     10       15      20
x6      6     12       18      24
x7      7     14       21      28
x8      8     16       24      32
x9      9     18       27      36

We can add a new column like this:

In [35]:
mt['byFive'] = 5 * np.arange(1, 10)

mt

byOne  byTwo  byThree  byFour  byFive
x1      1      2        3       4       5
x2      2      4        6       8      10
x3      3      6        9      12      15
x4      4      8       12      16      20
x5      5     10       15      20      25
x6      6     12       18      24      30
x7      7     14       21      28      35
x8      8     16       24      32      40
x9      9     18       27      36      45

And using the `.loc` we can add a new row like this:

In [36]:
mt.loc['x10'] = 10 * np.arange(1, 6)
mt

byOne  byTwo  byThree  byFour  byFive
x1       1      2        3       4       5
x2       2      4        6       8      10
x3       3      6        9      12      15
x4       4      8       12      16      20
x5       5     10       15      20      25
x6       6     12       18      24      30
x7       7     14       21      28      35
x8       8     16       24      32      40
x9       9     18       27      36      45
x10     10     20       30      40      50

### Dropping a column or a row from a DataFrame
We can use the `drop` method to remove a column from a DataFrame. Let's remove the column `byFive` we added above:

In [37]:
mt.drop(['byFive'], axis=1)

byOne  byTwo  byThree  byFour
x1       1      2        3       4
x2       2      4        6       8
x3       3      6        9      12
x4       4      8       12      16
x5       5     10       15      20
x6       6     12       18      24
x7       7     14       21      28
x8       8     16       24      32
x9       9     18       27      36
x10     10     20       30      40

Here `axis=1` referes to columns. To drop a row we use `axis=0` and provide a index instead of a column name.

In [38]:
mt.drop(['x10'], axis=0)

byOne  byTwo  byThree  byFour  byFive
x1      1      2        3       4       5
x2      2      4        6       8      10
x3      3      6        9      12      15
x4      4      8       12      16      20
x5      5     10       15      20      25
x6      6     12       18      24      30
x7      7     14       21      28      35
x8      8     16       24      32      40
x9      9     18       27      36      45

### DataFrame indexing and slicing
We can use the column names and indexes to access individual cells.

In [39]:
mt['byTwo']['x5']

10

To extract a single column, use its name:

In [40]:
mt['byThree']

x1      3
x2      6
x3      9
x4     12
x5     15
x6     18
x7     21
x8     24
x9     27
x10    30
Name: byThree, dtype: int64

And use an array of column names to extract multiple columns

In [41]:
mt[['byTwo', 'byFour']]

byTwo  byFour
x1       2       4
x2       4       8
x3       6      12
x4       8      16
x5      10      20
x6      12      24
x7      14      28
x8      16      32
x9      18      36
x10     20      40

Use `.loc` to access a specific row using its index:

In [42]:
mt.loc['x6']

byOne       6
byTwo      12
byThree    18
byFour     24
byFive     30
Name: x6, dtype: int64

Similarly we can extract rows using their index positiosn using `.iloc[]`. We can, for example extract the first row using the its index position `0` (the index itself is `x1`).

In [43]:
mt.iloc[0]

byOne      1
byTwo      2
byThree    3
byFour     4
byFive     5
Name: x1, dtype: int64

We can also use `.iloc` to access certain columns and rows based on their positions, much like the indexing and slicing of a two-dimensional numpy array. Here is the whole DataFrame:

In [44]:
mt.iloc[:, :]

byOne  byTwo  byThree  byFour  byFive
x1       1      2        3       4       5
x2       2      4        6       8      10
x3       3      6        9      12      15
x4       4      8       12      16      20
x5       5     10       15      20      25
x6       6     12       18      24      30
x7       7     14       21      28      35
x8       8     16       24      32      40
x9       9     18       27      36      45
x10     10     20       30      40      50

In the `[:, :]`, the first `:` refers to all rows and the second `:` refers to all columns.

Here is the slice from the third(position 2) row to the sixth (position 5) and from second column (position 1) to fifth column(position 4)

In [45]:
mt.iloc[2:5, 1:4]

byTwo  byThree  byFour
x3      6        9      12
x4      8       12      16
x5     10       15      20

And here is every other column and row.

In [46]:
mt.iloc[::2, ::2]

byOne  byThree  byFive
x1      1        3       5
x3      3        9      15
x5      5       15      25
x7      7       21      35
x9      9       27      45

Finally we can use the methods `head` and `tail` to display the first couple of records at the top or the bottom of a DataFrame. This is useful for exploring large dataframes.

In [47]:
print(mt.head())
print(mt.head(6))

print(mt.tail())
print(mt.tail(7))

    byOne  byTwo  byThree  byFour  byFive
x1      1      2        3       4       5
x2      2      4        6       8      10
x3      3      6        9      12      15
x4      4      8       12      16      20
x5      5     10       15      20      25
    byOne  byTwo  byThree  byFour  byFive
x1      1      2        3       4       5
x2      2      4        6       8      10
x3      3      6        9      12      15
x4      4      8       12      16      20
x5      5     10       15      20      25
x6      6     12       18      24      30
     byOne  byTwo  byThree  byFour  byFive
x6       6     12       18      24      30
x7       7     14       21      28      35
x8       8     16       24      32      40
x9       9     18       27      36      45
x10     10     20       30      40      50
     byOne  byTwo  byThree  byFour  byFive
x4       4      8       12      16      20
x5       5     10       15      20      25
x6       6     12       18      24      30
x7       7     14       

### Summarizing dataframes
Given the following 50 by 10 DataFrame:

In [48]:
data = pd.DataFrame(np.random.randn(50,10), columns=list('ABCDEFGHIJ'))

In [49]:
data

A         B         C         D         E         F         G  \
0  -0.259190  0.170754 -1.124605 -0.771915  0.973286 -0.946376  0.305876   
1  -0.976455 -0.472629  1.482042  1.802155  0.662279  0.645750 -0.178106   
2  -0.119066  1.017724  0.387901  1.951747 -0.452727 -0.433070 -1.549471   
3  -0.904966  0.121057 -0.590445  0.960849  0.284733  0.513823 -0.476244   
4  -0.528633 -0.560854 -0.930889  0.115935 -0.825676 -0.576343 -1.582058   
5  -0.817783 -0.896830  0.108925 -0.315767  1.115497  0.424926 -0.238312   
6  -0.147122  1.077447 -0.102460 -0.107177  0.314880  1.698336  0.776135   
7  -0.669262  0.434427 -0.017197 -0.683233 -0.537647  0.520835  0.303287   
8  -0.834004  0.883366 -1.273101 -0.254702  1.240292  1.192153  1.461381   
9  -0.684567  0.802311  0.930923 -0.165524  1.046815 -0.266683 -0.279070   
10 -1.413254 -0.113551 -0.098683 -0.226008  0.517509 -1.658974 -0.797651   
11 -1.398303  0.834655  1.932936  0.792200 -0.030750 -0.391471  1.599085   
12  1.597170 -0.733702 -0.461743  0.985242 -0.389422  2.209530  0.478019   
13 -0.816916  0.772642  1.086977 -1.369484  0.618693 -0.190263 -0.342597   
14  0.195233 -0.596947  0.965471 -1.333871 -0.500193 -0.000599 -0.680411   
15  0.660705 -0.708650  0.536850 -0.924158  0.714384 -2.856200 -0.656065   
16 -1.062444 -0.666166  1.886790 -1.797042 -0.344488  0.391635 -0.031518   
17 -0.650053  1.166369 -1.891905 -2.261109 -0.547639 -0.608037  0.347468   
18 -0.752158  0.232602  0.590905 -0.436220 -2.409686 -1.564827 -1.286187   
19  0.573365 -0.748543 -0.835685 -0.234671 -2.113597 -1.116338 -0.060612   
20  1.176843  0.057297 -0.323418  0.369775 -1.914552  0.262350 -0.637192   
21 -0.209290 -0.606882  0.693763 -1.882426 -0.684822 -1.030743  0.965688   
22  0.772936  1.671150  1.145047  0.608072 -0.447779 -0.306704  1.270623   
23 -1.968782  1.058383 -0.350883  1.207647  0.786918 -0.891231 -1.235076   
24 -0.608772 -1.224503  0.967387  1.171957 -0.649935  0.563515 -0.668121   
25 -1.338017  0.369573  0.252180 -0.639073  2.125620 -0.510489 -0.089911   
26  1.551536 -0.347166  1.668739  0.934935 -0.010354 -0.553926 -0.133094   
27 -0.451239  0.613035  0.314743 -0.085513 -0.635267 -0.425568 -0.651049   
28  1.393553 -1.766087 -0.484801 -0.579053 -0.271146 -0.878773 -0.742084   
29 -0.336865 -0.565155 -1.057572  0.281774 -0.527080  0.542339  0.037755   
30  0.702468 -0.248232 -1.184148  0.584779  0.103270  0.457034  1.369504   
31 -0.519484  1.237064 -0.031636 -1.543108 -0.692006 -0.233970 -0.644763   
32  0.062457 -0.981243  0.447691  1.236306 -1.501444  1.292967 -0.804052   
33 -0.156719 -1.091183  1.664423 -0.231749  1.331262  0.116011  0.108382   
34 -1.307061  0.947717 -0.823028 -0.177148 -0.836447  1.391394  0.842374   
35  0.679273  1.301921 -0.293242 -0.602255 -0.981548 -0.600490 -0.636663   
36  0.547691  0.356943  0.227978  2.585588  1.198930 -0.607902 -1.229509   
37 -1.046889 -0.275347  1.547125  0.162955 -0.956162 -0.084401  0.509041   
38  1.121889  1.397415 -0.401128 -0.729153 -1.183595  0.479804 -0.577125   
39 -0.184095 -1.135775  0.188527  0.328808  1.384745  1.180276 -0.327611   
40  0.363725 -2.468129 -0.031613  0.290612  0.083103  2.249411  0.273891   
41  0.077772  0.780231 -0.275987  2.768409 -0.297156 -0.964066 -0.168082   
42  0.014714 -0.046698 -0.251996 -0.082417 -0.154091 -0.546341 -0.311488   
43 -0.245146  1.686520  1.474020  0.832428 -1.204790  1.133447 -0.066480   
44 -0.184587  1.312425  1.441163  0.013772  0.781572 -1.326372 -1.897425   
45  0.282169  0.343365  1.578689 -0.600533 -0.522298  0.554261 -0.726182   
46  0.707604 -0.970614  0.042302 -1.823481  1.655602 -2.260195  0.815639   
47 -0.027832 -0.173137  0.512214  1.564469 -1.328802 -1.156235  0.368367   
48 -1.360113 -0.838715  2.364942  1.478743 -0.829626 -0.048703  0.532980   
49 -1.618905 -0.610666  0.103890  0.011803 -1.928664  1.043995 -1.207603   

           H         I         J  
0   0.583443 -0.610982 -1.349279  
1   0.756834 -0.975938  1.291805  
2  -0.362654  0.803287  0.037

We can statistically summarize it like this:

In [50]:
data.describe()

A          B          C          D          E          F  \
count  50.000000  50.000000  50.000000  50.000000  50.000000  50.000000   
mean   -0.222337   0.035980   0.274168   0.063683  -0.175400  -0.083430   
std     0.853798   0.940347   0.967988   1.117656   1.022266   1.053182   
min    -1.968782  -2.468129  -1.891905  -2.261109  -2.409686  -2.856200   
25%    -0.817566  -0.652291  -0.344017  -0.601825  -0.792258  -0.608003   
50%    -0.227218   0.005299   0.148726  -0.083965  -0.366955  -0.212117   
75%     0.343336   0.826569   0.966908   0.822371   0.651383   0.536963   
max     1.597170   1.686520   2.364942   2.768409   2.125620   2.249411   

               G          H          I          J  
count  50.000000  50.000000  50.000000  50.000000  
mean   -0.170926  -0.093148  -0.018117  -0.192426  
std     0.808752   0.945284   1.085262   0.800840  
min    -1.897425  -2.361269  -2.337900  -1.844480  
25%    -0.665107  -0.646771  -0.716275  -0.866149  
50%    -0.208209  -0.004306   0.117767  -0.233785  
75%     0.337070   0.500924   0.571871   0.343640  
max     1.599085   2.501638   3.020689   1.571183

We can also get the means of each column:

In [51]:
data.mean()

A   -0.222337
B    0.035980
C    0.274168
D    0.063683
E   -0.175400
F   -0.083430
G   -0.170926
H   -0.093148
I   -0.018117
J   -0.192426
dtype: float64

the variances of each column:

In [52]:
data.var()

A    0.728971
B    0.884252
C    0.937001
D    1.249154
E    1.045029
F    1.109192
G    0.654079
H    0.893562
I    1.177793
J    0.641345
dtype: float64

and the standard deviations of each column:

In [53]:
data.std()

A    0.853798
B    0.940347
C    0.967988
D    1.117656
E    1.022266
F    1.053182
G    0.808752
H    0.945284
I    1.085262
J    0.800840
dtype: float64

## Transposing DataFrames
We can transpose a DataFrame by reversing its columns and indexes.

In [54]:
data.transpose()

0         1         2         3         4         5         6   \
A -0.259190 -0.976455 -0.119066 -0.904966 -0.528633 -0.817783 -0.147122   
B  0.170754 -0.472629  1.017724  0.121057 -0.560854 -0.896830  1.077447   
C -1.124605  1.482042  0.387901 -0.590445 -0.930889  0.108925 -0.102460   
D -0.771915  1.802155  1.951747  0.960849  0.115935 -0.315767 -0.107177   
E  0.973286  0.662279 -0.452727  0.284733 -0.825676  1.115497  0.314880   
F -0.946376  0.645750 -0.433070  0.513823 -0.576343  0.424926  1.698336   
G  0.305876 -0.178106 -1.549471 -0.476244 -1.582058 -0.238312  0.776135   
H  0.583443  0.756834 -0.362654  0.506307  1.027357  0.834312 -1.096879   
I -0.610982 -0.975938  0.803287  1.818822  0.241012  1.036758  0.101428   
J -1.349279  1.291805  0.037094  0.741055  0.295293  0.570735 -1.019163   

         7         8         9   ...        40        41        42        43  \
A -0.669262 -0.834004 -0.684567  ...  0.363725  0.077772  0.014714 -0.245146   
B  0.434427  0.883366  0.802311  ... -2.468129  0.780231 -0.046698  1.686520   
C -0.017197 -1.273101  0.930923  ... -0.031613 -0.275987 -0.251996  1.474020   
D -0.683233 -0.254702 -0.165524  ...  0.290612  2.768409 -0.082417  0.832428   
E -0.537647  1.240292  1.046815  ...  0.083103 -0.297156 -0.154091 -1.204790   
F  0.520835  1.192153 -0.266683  ...  2.249411 -0.964066 -0.546341  1.133447   
G  0.303287  1.461381 -0.279070  ...  0.273891 -0.168082 -0.311488 -0.066480   
H -1.205196 -0.086144 -1.049862  ... -0.664565 -0.096246  0.354687  0.526044   
I -0.313493 -1.799382  0.510846  ...  0.821843 -0.431174  0.134107  1.258962   
J  1.381105  0.380367 -0.874103  ... -0.418738 -0.565806 -0.978821  0.593834   

         44        45        46        47        48        49  
A -0.184587  0.282169  0.707604 -0.027832 -1.360113 -1.618905  
B  1.312425  0.343365 -0.970614 -0.173137 -0.838715 -0.610666  
C  1.441163  1.578689  0.042302  0.512214  2.364942  0.103890  
D  0.013772 -0.600533 -1.823481  1.564469  1.478743  0.011803  
E  0.781572 -0.522298  1.655602 -1.328802 -0.829626 -1.928664  
F -1.326372  0.554261 -2.260195 -1.156235 -0.048703  1.043995  
G -1.897425 -0.726182  0.815639  0.368367  0.532980 -1.207603  
H -0.593388 -1.123454 -0.137665  0.181701  0.529484 -1.184310  
I  0.396543 -0.751372 -0.375808 -1.373649 -0.162104 -1.568484  
J  0.222624 -0.262738  0.325818 -0.340255 -0.920387 -0.882209  

[10 rows x 50 columns]

which is the same as:

In [55]:
data.T

0         1         2         3         4         5         6   \
A -0.259190 -0.976455 -0.119066 -0.904966 -0.528633 -0.817783 -0.147122   
B  0.170754 -0.472629  1.017724  0.121057 -0.560854 -0.896830  1.077447   
C -1.124605  1.482042  0.387901 -0.590445 -0.930889  0.108925 -0.102460   
D -0.771915  1.802155  1.951747  0.960849  0.115935 -0.315767 -0.107177   
E  0.973286  0.662279 -0.452727  0.284733 -0.825676  1.115497  0.314880   
F -0.946376  0.645750 -0.433070  0.513823 -0.576343  0.424926  1.698336   
G  0.305876 -0.178106 -1.549471 -0.476244 -1.582058 -0.238312  0.776135   
H  0.583443  0.756834 -0.362654  0.506307  1.027357  0.834312 -1.096879   
I -0.610982 -0.975938  0.803287  1.818822  0.241012  1.036758  0.101428   
J -1.349279  1.291805  0.037094  0.741055  0.295293  0.570735 -1.019163   

         7         8         9   ...        40        41        42        43  \
A -0.669262 -0.834004 -0.684567  ...  0.363725  0.077772  0.014714 -0.245146   
B  0.434427  0.883366  0.802311  ... -2.468129  0.780231 -0.046698  1.686520   
C -0.017197 -1.273101  0.930923  ... -0.031613 -0.275987 -0.251996  1.474020   
D -0.683233 -0.254702 -0.165524  ...  0.290612  2.768409 -0.082417  0.832428   
E -0.537647  1.240292  1.046815  ...  0.083103 -0.297156 -0.154091 -1.204790   
F  0.520835  1.192153 -0.266683  ...  2.249411 -0.964066 -0.546341  1.133447   
G  0.303287  1.461381 -0.279070  ...  0.273891 -0.168082 -0.311488 -0.066480   
H -1.205196 -0.086144 -1.049862  ... -0.664565 -0.096246  0.354687  0.526044   
I -0.313493 -1.799382  0.510846  ...  0.821843 -0.431174  0.134107  1.258962   
J  1.381105  0.380367 -0.874103  ... -0.418738 -0.565806 -0.978821  0.593834   

         44        45        46        47        48        49  
A -0.184587  0.282169  0.707604 -0.027832 -1.360113 -1.618905  
B  1.312425  0.343365 -0.970614 -0.173137 -0.838715 -0.610666  
C  1.441163  1.578689  0.042302  0.512214  2.364942  0.103890  
D  0.013772 -0.600533 -1.823481  1.564469  1.478743  0.011803  
E  0.781572 -0.522298  1.655602 -1.328802 -0.829626 -1.928664  
F -1.326372  0.554261 -2.260195 -1.156235 -0.048703  1.043995  
G -1.897425 -0.726182  0.815639  0.368367  0.532980 -1.207603  
H -0.593388 -1.123454 -0.137665  0.181701  0.529484 -1.184310  
I  0.396543 -0.751372 -0.375808 -1.373649 -0.162104 -1.568484  
J  0.222624 -0.262738  0.325818 -0.340255 -0.920387 -0.882209  

[10 rows x 50 columns]

### Sorting a DataFrame

We can sort indexes, column names, or the values of a DataFrame. For example, the following sorts the indexes (`axis=0`) of the DataFrame in an ascending order:

In [56]:
mt.sort_index(axis=0)

byOne  byTwo  byThree  byFour  byFive
x1       1      2        3       4       5
x10     10     20       30      40      50
x2       2      4        6       8      10
x3       3      6        9      12      15
x4       4      8       12      16      20
x5       5     10       15      20      25
x6       6     12       18      24      30
x7       7     14       21      28      35
x8       8     16       24      32      40
x9       9     18       27      36      45

The following sorts the columns (`axis=1`) of the DataFrame in a descending order:

In [57]:
mt.sort_index(axis=1, ascending=False)

byTwo  byThree  byOne  byFour  byFive
x1       2        3      1       4       5
x2       4        6      2       8      10
x3       6        9      3      12      15
x4       8       12      4      16      20
x5      10       15      5      20      25
x6      12       18      6      24      30
x7      14       21      7      28      35
x8      16       24      8      32      40
x9      18       27      9      36      45
x10     20       30     10      40      50

Here is how to sort the values a given a column

In [58]:
mt.sort_values('byThree', ascending=False)

byOne  byTwo  byThree  byFour  byFive
x10     10     20       30      40      50
x9       9     18       27      36      45
x8       8     16       24      32      40
x7       7     14       21      28      35
x6       6     12       18      24      30
x5       5     10       15      20      25
x4       4      8       12      16      20
x3       3      6        9      12      15
x2       2      4        6       8      10
x1       1      2        3       4       5

and here is how to sort a value of a given row

In [59]:
mt.sort_values('x5', ascending=False, axis=1)

byFive  byFour  byThree  byTwo  byOne
x1        5       4        3      2      1
x2       10       8        6      4      2
x3       15      12        9      6      3
x4       20      16       12      8      4
x5       25      20       15     10      5
x6       30      24       18     12      6
x7       35      28       21     14      7
x8       40      32       24     16      8
x9       45      36       27     18      9
x10      50      40       30     20     10

## CHALLENGE 01
Recreate the 12 times table (see https://www.mathsisfun.com/tables.html) one column at a time. Start by creating an empty DataFrame representing the table. Use a Series object to create the first column and add it to the table. Move on the next column and do the same. And so on for the remaining columns. Use may use loops and expressions to calculate the values of these columns and avoid hard-coding values and code repetition.

In [60]:
# TODO