# 02.A: Working with Datasets
It's important to have clear and sensible way of representing the datasets that learning algorithms train on.

A dataset consists of $n$ examples. Each example consists of $m$ features. The number of these features per example $m$ is also the number dimensions the dataset has. In supervised learning, the dataset is a matrix like this:


$\boldsymbol{D} =\left[\begin{array}{cccccc} 
  x_1^{(1)} & x_2^{(1)} & x_3^{(1)} & \cdots & x_m^{(1)} & y^{(1)}\\ 
  x_1^{(2)} & x_2^{(2)} & x_3^{(2)} & \cdots & x_m^{(2)} & y^{(2)}\\
  x_1^{(3)} & x_2^{(3)} & x_3^{(3)} & \cdots & x_m^{(3)} & y^{(3)}\\
  \vdots    & \vdots    & \vdots    & \cdots & \vdots & \vdots \\
  x_1^{(n)} & x_2^{(n)} & x_3^{(n)} & \cdots & x_m^{(n)} & y^{(n)}
\end{array}\right]$

Each row of this matrix consists of the $m$ features plus the target label as the last element in the row. In other words, $\boldsymbol{D}$ consists of both the input matrix $\boldsymbol{X}$ and target vector $y$, where: 

$\boldsymbol{X} =\left[\begin{array}{ccccc} 
  x_1^{(1)} & x_2^{(1)} & x_3^{(1)} & \cdots & x_m^{(1)}\\ 
  x_1^{(2)} & x_2^{(2)} & x_3^{(2)} & \cdots & x_m^{(2)}\\
  x_1^{(3)} & x_2^{(3)} & x_3^{(3)} & \cdots & x_m^{(3)}\\
  \vdots    & \vdots    & \vdots    & \cdots & \vdots \\
  x_1^{(n)} & x_2^{(n)} & x_3^{(n)} & \cdots & x_m^{(n)}
\end{array}\right]$

and

$\boldsymbol{y} =\left[\begin{array}{c} 
  y^{(1)}\\ 
  y^{(2)}\\
  y^{(3)}\\
  \vdots \\
  y^{(n)}
\end{array}\right]$

For unsupervised learning, $\boldsymbol{D}$ is the same as $\boldsymbol{X}$. Here is a class named `DataSet` to represent datasets. It uses pandas' DataFrame.

In addition, features have names

In [1]:
import numpy as np
import pandas as pd

In [2]:
class DataSet:
    """
    A dataset for a machine learning problem. A dataset d has the following properties:
    d.examples   A list of examples. Each one contains both the features and the target.
    d.features   An array of the of feature names.
    d.target     An m by 1 array containing the values of y
    d.y          Same as d.target
    d.inputs     An n by m array containing the values of X
    d.X          Same as d.inputs
    d.N          Number of examples
    d.M          Number of dimensions
    d.name       The name of the data set (for output display only)
    
    """
    def __init__(self, data, features=None, y=None, name=None):
        """
        If y is True, the data contains the target as the last column
        If y is None or False, No target is available
        Else y is an array to be added as the last column of the examples  dataframe
        """
        self.__name = name
        if isinstance(data, pd.DataFrame):
            self.__examples = data
        else:
            self.__examples = pd.DataFrame(data, columns=features)
            
        if y is True:
            self.__examples.columns = [*self.__examples.columns[:-1], 'y']
        elif y is not False and y is not None:
            self.__examples['y'] = y
            
    
    @property
    def examples(self):
        return self.__examples
    
    @property
    def features(self):
        return self.__examples.columns[:-1].values
    
    @property
    def target(self):
        if 'y' in self.__examples.columns:
            return self.__examples['y'].values
        return None
    
    @property
    def y(self):
        return self.target
    
    @property
    def inputs(self):
        return self.__examples.iloc[:, :-1].values
    
    @property
    def X(self):
        return self.inputs
    
    @property
    def name(self):
        return self.__name
    
    @property
    def N(self):
        return self.__examples.shape[0]
    
    @property
    def M(self):
        return self.inputs.shape[1]
    
    def __repr__(self):
        return repr(self.examples)

Let's test this class by creating a $27 \times 3$ input data and a separate $y$ column.

In [3]:
ds = DataSet(np.array([
    np.random.randint(2,9, 27),
    np.random.randint(1,9, 27),
    np.random.normal(loc=10, scale=2, size=27)
]).T, features=['x1', 'x2', 'x1'], y=np.random.randint(0,2, 27), name="Sample Data")

ds

     x1   x2         x1  y
0   8.0  4.0  11.178737  1
1   2.0  8.0  12.256604  1
2   8.0  2.0  10.904968  0
3   2.0  6.0   5.873100  1
4   3.0  1.0  12.481141  0
5   8.0  6.0   8.366142  1
6   6.0  2.0   9.566010  1
7   8.0  4.0  10.400661  0
8   6.0  2.0   6.382902  0
9   3.0  3.0   8.238208  1
10  4.0  5.0  11.560653  1
11  7.0  3.0   9.232481  1
12  6.0  4.0  12.914182  0
13  3.0  7.0  11.739318  1
14  4.0  7.0  12.307112  0
15  4.0  3.0  12.128416  1
16  2.0  3.0   8.648244  0
17  6.0  4.0   8.990001  0
18  6.0  7.0   6.007080  0
19  7.0  2.0  10.326726  0
20  6.0  5.0   7.980929  0
21  3.0  6.0  11.199824  1
22  5.0  8.0  10.641220  0
23  8.0  3.0   9.746894  1
24  7.0  4.0   8.324551  1
25  4.0  6.0  11.444388  0
26  8.0  7.0   8.626009  1

In [4]:
ds.examples

x1   x2         x1  y
0   8.0  4.0  11.178737  1
1   2.0  8.0  12.256604  1
2   8.0  2.0  10.904968  0
3   2.0  6.0   5.873100  1
4   3.0  1.0  12.481141  0
5   8.0  6.0   8.366142  1
6   6.0  2.0   9.566010  1
7   8.0  4.0  10.400661  0
8   6.0  2.0   6.382902  0
9   3.0  3.0   8.238208  1
10  4.0  5.0  11.560653  1
11  7.0  3.0   9.232481  1
12  6.0  4.0  12.914182  0
13  3.0  7.0  11.739318  1
14  4.0  7.0  12.307112  0
15  4.0  3.0  12.128416  1
16  2.0  3.0   8.648244  0
17  6.0  4.0   8.990001  0
18  6.0  7.0   6.007080  0
19  7.0  2.0  10.326726  0
20  6.0  5.0   7.980929  0
21  3.0  6.0  11.199824  1
22  5.0  8.0  10.641220  0
23  8.0  3.0   9.746894  1
24  7.0  4.0   8.324551  1
25  4.0  6.0  11.444388  0
26  8.0  7.0   8.626009  1

In [5]:
ds.features

array(['x1', 'x2', 'x1'], dtype=object)

In [6]:
ds.target 

array([1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 1, 1, 0, 1])

In [7]:
ds.y 

array([1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 1, 1, 0, 1])

In [8]:
ds.inputs

array([[ 8.        ,  4.        , 11.17873652],
       [ 2.        ,  8.        , 12.25660397],
       [ 8.        ,  2.        , 10.90496816],
       [ 2.        ,  6.        ,  5.87309977],
       [ 3.        ,  1.        , 12.48114054],
       [ 8.        ,  6.        ,  8.36614168],
       [ 6.        ,  2.        ,  9.56600954],
       [ 8.        ,  4.        , 10.40066147],
       [ 6.        ,  2.        ,  6.38290222],
       [ 3.        ,  3.        ,  8.23820751],
       [ 4.        ,  5.        , 11.56065281],
       [ 7.        ,  3.        ,  9.2324811 ],
       [ 6.        ,  4.        , 12.91418164],
       [ 3.        ,  7.        , 11.73931805],
       [ 4.        ,  7.        , 12.3071121 ],
       [ 4.        ,  3.        , 12.12841607],
       [ 2.        ,  3.        ,  8.64824434],
       [ 6.        ,  4.        ,  8.99000096],
       [ 6.        ,  7.        ,  6.00707974],
       [ 7.        ,  2.        , 10.32672609],
       [ 6.        ,  5.        ,  7.980

In [9]:
ds.X

array([[ 8.        ,  4.        , 11.17873652],
       [ 2.        ,  8.        , 12.25660397],
       [ 8.        ,  2.        , 10.90496816],
       [ 2.        ,  6.        ,  5.87309977],
       [ 3.        ,  1.        , 12.48114054],
       [ 8.        ,  6.        ,  8.36614168],
       [ 6.        ,  2.        ,  9.56600954],
       [ 8.        ,  4.        , 10.40066147],
       [ 6.        ,  2.        ,  6.38290222],
       [ 3.        ,  3.        ,  8.23820751],
       [ 4.        ,  5.        , 11.56065281],
       [ 7.        ,  3.        ,  9.2324811 ],
       [ 6.        ,  4.        , 12.91418164],
       [ 3.        ,  7.        , 11.73931805],
       [ 4.        ,  7.        , 12.3071121 ],
       [ 4.        ,  3.        , 12.12841607],
       [ 2.        ,  3.        ,  8.64824434],
       [ 6.        ,  4.        ,  8.99000096],
       [ 6.        ,  7.        ,  6.00707974],
       [ 7.        ,  2.        , 10.32672609],
       [ 6.        ,  5.        ,  7.980

In [10]:
ds.name

'Sample Data'

In [11]:
ds.N

27

In [12]:
ds.M

3

## Shuffling
We can also supplement this class with a few useful methods. One such method is for shuffling.

In [13]:
class DataSet:
    """
    A dataset for a machine learning problem. A dataset d has the following properties:
    d.examples   A list of examples. Each one contains both the features and the target.
    d.features   An array of the of feature names.
    d.target     An m by 1 array containing the values of y
    d.y          Same as d.target
    d.inputs     An n by m array containing the values of X
    d.X          Same as d.inputs
    d.N          Number of examples
    d.M          Number of dimensions
    d.name       The name of the data set (for output display only)
    
    """
    def __init__(self, data, features=None, y=None, name=None):
        """
        If y is True, the data contains the target as the last column
        If y is None or False, No target is available
        Else y is an array to be added as the last column of the examples  dataframe
        """
        self.__name = name
        if isinstance(data, pd.DataFrame):
            self.__examples = data
        else:
            self.__examples = pd.DataFrame(data, columns=features)
            
        if y is True:
            self.__examples.columns = [*self.__examples.columns[:-1], 'y']
        elif y is not False and y is not None:
            self.__examples['y'] = y
            
    @property
    def examples(self):
        return self.__examples
    
    @property
    def features(self):
        return self.__examples.columns[:-1].values
    
    @property
    def target(self):
        if 'y' in self.__examples.columns:
            return self.__examples['y'].values
        return None
    
    @property
    def y(self):
        return self.target
    
    @property
    def inputs(self):
        return self.__examples.iloc[:, :-1].values
    
    @property
    def X(self):
        return self.inputs
    
    @property
    def name(self):
        return self.__name
    
    @property
    def N(self):
        return self.__examples.shape[0]
    
    @property
    def M(self):
        return self.inputs.shape[1]
    
    def shuffled(self, random_state=None):
        rgen = np.random.RandomState(random_state)
        indexes = np.arange(self.N)
        rgen.shuffle(indexes)
        return DataSet(self.__examples.iloc[indexes])
    
    def __repr__(self):
        return repr(self.examples)

In [14]:
ds = DataSet(np.array([
    np.random.randint(2,9, 27),
    np.random.randint(1,9, 27),
    np.random.normal(loc=10, scale=2, size=27)
]).T, features=['x1', 'x2', 'x1'], y=np.random.randint(0,2, 27), name="Sample Data")


ds.shuffled()

     x1   x2         x1  y
16  4.0  7.0   5.714344  0
21  5.0  8.0   5.385856  1
15  5.0  1.0   8.354670  0
23  5.0  5.0   7.850704  0
18  5.0  8.0  11.031393  0
26  6.0  6.0  10.549901  0
11  5.0  3.0   7.395555  1
24  3.0  8.0   9.932185  0
10  6.0  7.0   9.003475  0
19  8.0  3.0  10.456021  0
12  3.0  4.0  12.315832  1
7   6.0  7.0  10.960670  0
9   2.0  2.0   9.986579  0
17  4.0  5.0   7.442021  1
4   4.0  5.0  14.251876  0
1   6.0  2.0   7.965331  1
5   2.0  5.0   9.649350  1
8   3.0  1.0  12.959148  0
3   2.0  6.0   8.153702  1
20  4.0  4.0  11.669658  1
22  3.0  3.0   7.957762  1
0   2.0  7.0  14.706965  0
14  4.0  8.0  11.845854  0
2   7.0  3.0  10.695755  1
25  5.0  1.0  13.858476  1
6   7.0  7.0   6.829497  1
13  8.0  3.0  14.586365  1

## Splitting a dataset into training and test datasets
Another method is that for splitting the  dataset into a training and test sets.

In [15]:
class DataSet:
    """
    A dataset for a machine learning problem. A dataset d has the following properties:
    d.examples   A list of examples. Each one contains both the features and the target.
    d.features   An array of the of feature names.
    d.target     An m by 1 array containing the values of y
    d.y          Same as d.target
    d.inputs     An n by m array containing the values of X
    d.X          Same as d.inputs
    d.N          Number of examples
    d.M          Number of dimensions
    d.name       The name of the data set (for output display only)
    """
    def __init__(self, data, features=None, y=None, name=None):
        """
        If y is True, the data contains the target as the last column
        If y is None or False, No target is available
        Else y is an array to be added as the last column of the examples  dataframe
        """
        self.__name = name
        if isinstance(data, pd.DataFrame):
            self.__examples = data
        else:
            self.__examples = pd.DataFrame(data, columns=features)
            
        if y is True:
            self.__examples.columns = [*self.__examples.columns[:-1], 'y']
        elif y is not False and y is not None:
            self.__examples['y'] = y
            
    
    @property
    def examples(self):
        return self.__examples
    
    @property
    def features(self):
        return self.__examples.columns[:-1].values
    
    @property
    def target(self):
        if 'y' in self.__examples.columns:
            return self.__examples['y'].values
        return None
    
    @property
    def y(self):
        return self.target
    
    @property
    def inputs(self):
        return self.__examples.iloc[:, :-1].values
    
    @property
    def X(self):
        return self.inputs
    
    @property
    def name(self):
        return self.__name
    
    @property
    def N(self):
        return self.__examples.shape[0]
    
    @property
    def M(self):
        return self.inputs.shape[1]
    
    def shuffled(self, random_state=None):
        rgen = np.random.RandomState(random_state)
        indexes = np.arange(self.N)
        rgen.shuffle(indexes)
        return DataSet(self.__examples.iloc[indexes])
    
    def train_test_split(self,start=0, end=None, test_portion=None, shuffle=False, random_state=None):
        """
        Splits the dataset into a training set and atest set. 
        If test_portion is specified, return that portion of the dataset as test 
        and the rest as training. 
        Otherwise, return the examples between start and end as test and the 
        rest as training.
        """
        indexes = np.arange(self.N)
        if shuffle is True:
            rgen = np.random.RandomState(random_state)
            rgen.shuffle(indexes)

        if test_portion is None:
            end = end or self.N
        else:
            if not isinstance(test_portion, float) or test_portion < 0 or test_portion > 1:
                raise TypeError("Only fractions between ]0,1[ are allowed")

            start = self.N - int(self.N * test_portion)
            end = self.N

        test = my.DataSet(self.examples.iloc[indexes[range(start, end)]])
        train = my.DataSet(pd.concat([self.examples.iloc[indexes[range(start)]], 
                                      self.examples.iloc[indexes[range(end, self.N)]]], axis=0))    
        return train, test
    
    def __repr__(self):
        return repr(self.examples)

In [16]:
ds = DataSet(np.array([
    np.random.randint(2,9, 27),
    np.random.randint(1,9, 27),
    np.random.normal(loc=10, scale=2, size=27)
]).T, features=['x1', 'x2', 'x1'], y=np.random.randint(0,2, 27), name="Sample Data")


ta, te = ds.train_test_split(test_portion=.25, shuffle=False, random_state=17)
print(ta)
print(te)

NameError: name 'my' is not defined

## CHALLENGE
Provide an implementation for the `train_validation_test_split` method below. This method should split the data into three sets: training, validation, and test. You may use `train_test_split` method. Make sure to include a comment describing how your implementation of the method works. Test your method on the `ds` dataset above and show that it works.

In [ ]:
import numpy as np
import pandas as pd

class DataSet:
    """
    A dataset for a machine learning problem. A dataset d has the following properties:
    d.examples   A list of examples. Each one contains both the features and the target.
    d.features   An array of the of feature names.
    d.target     An m by 1 array containing the values of y
    d.y          Same as d.target
    d.inputs     An n by m array containing the values of X
    d.X          Same as d.inputs
    d.N          Number of examples
    d.M          Number of dimensions
    d.name       The name of the data set (for output display only)
    
    """
    def __init__(self, data, features=None, y=None, name=None):
        """
        If y is True, the data contains the target as the last column
        If y is None or False, No target is available
        Else y is an array to be added as the last column of the examples  dataframe
        """
        self.__name = name
        if isinstance(data, pd.DataFrame):
            self.__examples = data
        else:
            self.__examples = pd.DataFrame(data, columns=features)
            
        if y is True:
            self.__examples.columns = [*self.__examples.columns[:-1], 'y']
        elif y is not False and y is not None:
            self.__examples['y'] = y
            
    
    @property
    def examples(self):
        return self.__examples
    
    @property
    def features(self):
        return self.__examples.columns[:-1].values
    
    @property
    def target(self):
        if 'y' in self.__examples.columns:
            return self.__examples['y'].values
        return None
    
    @property
    def y(self):
        return self.target
    
    @property
    def inputs(self):
        return self.__examples.iloc[:, :-1].values
    
    @property
    def X(self):
        return self.inputs
    
    @property
    def name(self):
        return self.__name
    
    @property
    def N(self):
        return self.__examples.shape[0]
    
    @property
    def M(self):
        return self.inputs.shape[1]
    
    def shuffled(self, random_state=None):
        rgen = np.random.RandomState(random_state)
        indexes = np.arange(self.N)
        rgen.shuffle(indexes)
        return DataSet(self.__examples.iloc[indexes])
    
    def train_test_split(self,start=0, end=None, test_portion=None, shuffle=False, random_state=None):
        """
        Splits the dataset into a training set and atest set. 
        If test_portion is specified, return that portion of the dataset as test 
        and the rest as training. 
        Otherwise, return the examples between start and end as test and the 
        rest as training.
        """
        indexes = np.arange(self.N)
        if shuffle is True:
            rgen = np.random.RandomState(random_state)
            rgen.shuffle(indexes)

        if test_portion is None:
            end = end or self.N
        else:
            if not isinstance(test_portion, float) or test_portion < 0 or test_portion > 1:
                raise TypeError("Only fractions between ]0,1[ are allowed")

            start = self.N - int(self.N * test_portion)
            end = self.N

        test = my.DataSet(self.examples.iloc[indexes[range(start, end)]])
        train = my.DataSet(pd.concat([self.examples.iloc[indexes[range(start)]], 
                                      self.examples.iloc[indexes[range(end, self.N)]]], axis=0))    
        return train, test
    
    def train_validation_test_split(self, validation_portion=.25, test_portion=.25, shuffle=False, random_state=None):
        # TODO
        pass
    
    def __repr__(self):
        return repr(self.examples)